name: egorka
description: Egorka

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  flutter_pdfview: ^1.2.7
  yandex_mapkit: ^3.2.0
  mask_text_input_formatter: ^2.4.0
  flutter_svg: ^1.0.3
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  path_provider: ^2.0.2
  url_launcher: ^6.1.7
  webview_flutter: ^4.0.2
  geocoding: ^2.0.5
  geocoder2: ^1.4.0
  flutter_localization: ^0.1.9
  open_file: ^3.2.1
  flutter_bloc: ^8.1.1
  flutter_screenutil: ^5.5.4
  shared_preferences: ^2.0.15
  rounded_loading_button: ^2.0.8
  geolocator: ^9.0.2
  sliding_up_panel: ^2.0.0+1
  permission_handler: ^10.1.0
  flutter_polyline_points: ^1.0.0
  scale_button: ^2.1.2
  custom_map_markers: ^0.0.2+1
  intl: ^0.17.0
  flip_card: ^0.6.0
  blur: ^3.1.0
  flutter_secure_storage: ^6.0.0
  get_ip_address: ^0.0.5
  flutter_smart_dialog: ^4.5.3+2
  flutter_vector_icons: ^1.0.0
  keyboard_actions: ^4.0.1
  lottie: ^2.0.0
  firebase_core: ^2.3.0
  firebase_messaging: ^14.1.3
  data_connection_checker_nulls: ^0.0.2
  animated_text_kit: ^4.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/anim/
    - assets/files/
